services:
  kafka:
    image: bitnami/kafka:4.0
    container_name: java-order-service-kafka
    ports:
      - "19092:19092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:19092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_KRAFT_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  kafka-init:
    image: bitnami/kafka:4.0
    container_name: java-order-service-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"
    entrypoint:
      - /bin/bash
      - -ec
      - |
        /opt/bitnami/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic orders.created.v1 \
          --partitions 3 \
          --replication-factor 1

        /opt/bitnami/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic orders.cancelled.v1 \
          --partitions 3 \
          --replication-factor 1

        /opt/bitnami/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic payments.requested.v1 \
          --partitions 3 \
          --replication-factor 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: java-order-service-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
